apiVersion: alibabacloud.com/v1
kind: AlbConfig
metadata:
  name: hk-idc-alb
spec:
  config:
    name: hk-idc-alb
    addressType: Intranet
    zoneMappings:
    - vSwitchId: vsw-j6cdylo2medu5bi9mdyrr
    - vSwitchId: vsw-j6c7spm122hut8iuwi94x
