@startuml
' user_com_gmas -> Bob: Another authentication Request
user_com_gmas -> user_center_service: 获取登录token （/login/sms/smsVerify）
user_center_service --> BPM: 查询开户进度信息
user_center_service --> CMS: 查询CMS保存的账户类型/南北向通信息

user_com_gmas <-- user_center_service
@enduml